/* Country catalogue from https://www.ipdeny.com/ipblocks/.
 * Names and ISO codes only; no IP data is bundled. */
static const struct
{
    const char *code;
    const wchar_t *name;
} country_list[] = {
    { "AF", L"Afghanistan (AF)" },
    { "AL", L"Albania (AL)" },
    { "DZ", L"Algeria (DZ)" },
    { "AS", L"American Samoa (AS)" },
    { "AD", L"Andorra (AD)" },
    { "AO", L"Angola (AO)" },
    { "AI", L"Anguilla (AI)" },
    { "AQ", L"Antarctica (AQ)" },
    { "AG", L"Antigua And Barbuda (AG)" },
    { "AR", L"Argentina (AR)" },
    { "AM", L"Armenia (AM)" },
    { "AW", L"Aruba (AW)" },
    { "AU", L"Australia (AU)" },
    { "AT", L"Austria (AT)" },
    { "AZ", L"Azerbaijan (AZ)" },
    { "BS", L"Bahamas (BS)" },
    { "BH", L"Bahrain (BH)" },
    { "BD", L"Bangladesh (BD)" },
    { "BB", L"Barbados (BB)" },
    { "BY", L"Belarus (BY)" },
    { "BE", L"Belgium (BE)" },
    { "BZ", L"Belize (BZ)" },
    { "BJ", L"Benin (BJ)" },
    { "BM", L"Bermuda (BM)" },
    { "BT", L"Bhutan (BT)" },
    { "BO", L"Bolivia (BO)" },
    { "BA", L"Bosnia And Herzegovina (BA)" },
    { "BW", L"Botswana (BW)" },
    { "BR", L"Brazil (BR)" },
    { "IO", L"British Indian Ocean Territory (IO)" },
    { "BN", L"Brunei Darussalam (BN)" },
    { "BG", L"Bulgaria (BG)" },
    { "BF", L"Burkina Faso (BF)" },
    { "BI", L"Burundi (BI)" },
    { "KH", L"Cambodia (KH)" },
    { "CM", L"Cameroon (CM)" },
    { "CA", L"Canada (CA)" },
    { "CV", L"Cape Verde (CV)" },
    { "KY", L"Cayman Islands (KY)" },
    { "CF", L"Central African Republic (CF)" },
    { "TD", L"Chad (TD)" },
    { "CL", L"Chile (CL)" },
    { "CN", L"China (CN)" },
    { "CC", L"Cocos (Keeling) Islands (CC)" },
    { "CO", L"Colombia (CO)" },
    { "KM", L"Comoros (KM)" },
    { "CG", L"Congo (CG)" },
    { "CD", L"Congo, The Democratic Republic Of The (CD)" },
    { "CK", L"Cook Islands (CK)" },
    { "CR", L"Costa Rica (CR)" },
    { "CI", L"Cote D'Ivoire (CI)" },
    { "HR", L"Croatia (HR)" },
    { "CU", L"Cuba (CU)" },
    { "CY", L"Cyprus (CY)" },
    { "CZ", L"Czech Republic (CZ)" },
    { "DK", L"Denmark (DK)" },
    { "DJ", L"Djibouti (DJ)" },
    { "DM", L"Dominica (DM)" },
    { "DO", L"Dominican Republic (DO)" },
    { "EC", L"Ecuador (EC)" },
    { "EG", L"Egypt (EG)" },
    { "SV", L"El Salvador (SV)" },
    { "GQ", L"Equatorial Guinea (GQ)" },
    { "ER", L"Eritrea (ER)" },
    { "EE", L"Estonia (EE)" },
    { "ET", L"Ethiopia (ET)" },
    { "FK", L"Falkland Islands (Malvinas) (FK)" },
    { "FO", L"Faroe Islands (FO)" },
    { "FJ", L"Fiji (FJ)" },
    { "FI", L"Finland (FI)" },
    { "FR", L"France (FR)" },
    { "GF", L"French Guiana (GF)" },
    { "PF", L"French Polynesia (PF)" },
    { "GA", L"Gabon (GA)" },
    { "GM", L"Gambia (GM)" },
    { "GE", L"Georgia (GE)" },
    { "DE", L"Germany (DE)" },
    { "GH", L"Ghana (GH)" },
    { "GI", L"Gibraltar (GI)" },
    { "GR", L"Greece (GR)" },
    { "GL", L"Greenland (GL)" },
    { "GD", L"Grenada (GD)" },
    { "GP", L"Guadeloupe (GP)" },
    { "GU", L"Guam (GU)" },
    { "GT", L"Guatemala (GT)" },
    { "GN", L"Guinea (GN)" },
    { "GW", L"Guinea-Bissau (GW)" },
    { "GY", L"Guyana (GY)" },
    { "HT", L"Haiti (HT)" },
    { "VA", L"Holy See (Vatican City State) (VA)" },
    { "HN", L"Honduras (HN)" },
    { "HK", L"Hong Kong (HK)" },
    { "HU", L"Hungary (HU)" },
    { "IS", L"Iceland (IS)" },
    { "IN", L"India (IN)" },
    { "ID", L"Indonesia (ID)" },
    { "IR", L"Iran, Islamic Republic Of (IR)" },
    { "IQ", L"Iraq (IQ)" },
    { "IE", L"Ireland (IE)" },
    { "IM", L"Isle Of Man (IM)" },
    { "IL", L"Israel (IL)" },
    { "IT", L"Italy (IT)" },
    { "JM", L"Jamaica (JM)" },
    { "JP", L"Japan (JP)" },
    { "JE", L"Jersey (JE)" },
    { "JO", L"Jordan (JO)" },
    { "KZ", L"Kazakhstan (KZ)" },
    { "KE", L"Kenya (KE)" },
    { "KI", L"Kiribati (KI)" },
    { "KP", L"Korea, Democratic People'S Republic Of (KP)" },
    { "KR", L"Korea, Republic Of (KR)" },
    { "KW", L"Kuwait (KW)" },
    { "KG", L"Kyrgyzstan (KG)" },
    { "AX", L"Land Islands (AX)" },
    { "LA", L"Lao People'S Democratic Republic (LA)" },
    { "LV", L"Latvia (LV)" },
    { "LB", L"Lebanon (LB)" },
    { "LS", L"Lesotho (LS)" },
    { "LR", L"Liberia (LR)" },
    { "LY", L"Libyan Arab Jamahiriya (LY)" },
    { "LI", L"Liechtenstein (LI)" },
    { "LT", L"Lithuania (LT)" },
    { "LU", L"Luxembourg (LU)" },
    { "MO", L"Macao (MO)" },
    { "MK", L"Macedonia, The Former Yugoslav Republic Of (MK)" },
    { "MG", L"Madagascar (MG)" },
    { "MW", L"Malawi (MW)" },
    { "MY", L"Malaysia (MY)" },
    { "MV", L"Maldives (MV)" },
    { "ML", L"Mali (ML)" },
    { "MT", L"Malta (MT)" },
    { "MH", L"Marshall Islands (MH)" },
    { "MQ", L"Martinique (MQ)" },
    { "MR", L"Mauritania (MR)" },
    { "MU", L"Mauritius (MU)" },
    { "YT", L"Mayotte (YT)" },
    { "MX", L"Mexico (MX)" },
    { "FM", L"Micronesia, Federated States Of (FM)" },
    { "MD", L"Moldova, Republic Of (MD)" },
    { "MC", L"Monaco (MC)" },
    { "MN", L"Mongolia (MN)" },
    { "ME", L"Montenegro (ME)" },
    { "MS", L"Montserrat (MS)" },
    { "MA", L"Morocco (MA)" },
    { "MZ", L"Mozambique (MZ)" },
    { "MM", L"Myanmar (MM)" },
    { "NA", L"Namibia (NA)" },
    { "NR", L"Nauru (NR)" },
    { "NP", L"Nepal (NP)" },
    { "NL", L"Netherlands (NL)" },
    { "NC", L"New Caledonia (NC)" },
    { "NZ", L"New Zealand (NZ)" },
    { "NI", L"Nicaragua (NI)" },
    { "NE", L"Niger (NE)" },
    { "NG", L"Nigeria (NG)" },
    { "NU", L"Niue (NU)" },
    { "NF", L"Norfolk Island (NF)" },
    { "MP", L"Northern Mariana Islands (MP)" },
    { "NO", L"Norway (NO)" },
    { "OM", L"Oman (OM)" },
    { "PK", L"Pakistan (PK)" },
    { "PW", L"Palau (PW)" },
    { "PS", L"Palestinian Territory, Occupied (PS)" },
    { "PA", L"Panama (PA)" },
    { "PG", L"Papua New Guinea (PG)" },
    { "PY", L"Paraguay (PY)" },
    { "PE", L"Peru (PE)" },
    { "PH", L"Philippines (PH)" },
    { "PL", L"Poland (PL)" },
    { "PT", L"Portugal (PT)" },
    { "PR", L"Puerto Rico (PR)" },
    { "QA", L"Qatar (QA)" },
    { "RE", L"Reunion (RE)" },
    { "RO", L"Romania (RO)" },
    { "RU", L"Russian Federation (RU)" },
    { "RW", L"Rwanda (RW)" },
    { "KN", L"Saint Kitts And Nevis (KN)" },
    { "LC", L"Saint Lucia (LC)" },
    { "PM", L"Saint Pierre And Miquelon (PM)" },
    { "VC", L"Saint Vincent And The Grenadines (VC)" },
    { "WS", L"Samoa (WS)" },
    { "SM", L"San Marino (SM)" },
    { "ST", L"Sao Tome And Principe (ST)" },
    { "SA", L"Saudi Arabia (SA)" },
    { "SN", L"Senegal (SN)" },
    { "RS", L"Serbia (RS)" },
    { "SC", L"Seychelles (SC)" },
    { "SL", L"Sierra Leone (SL)" },
    { "SG", L"Singapore (SG)" },
    { "SK", L"Slovakia (SK)" },
    { "SI", L"Slovenia (SI)" },
    { "SB", L"Solomon Islands (SB)" },
    { "SO", L"Somalia (SO)" },
    { "ZA", L"South Africa (ZA)" },
    { "ES", L"Spain (ES)" },
    { "LK", L"Sri Lanka (LK)" },
    { "SD", L"Sudan (SD)" },
    { "SR", L"Suriname (SR)" },
    { "SZ", L"Swaziland (SZ)" },
    { "SE", L"Sweden (SE)" },
    { "CH", L"Switzerland (CH)" },
    { "SY", L"Syrian Arab Republic (SY)" },
    { "TW", L"Taiwan (TW)" },
    { "TJ", L"Tajikistan (TJ)" },
    { "TZ", L"Tanzania, United Republic Of (TZ)" },
    { "TH", L"Thailand (TH)" },
    { "TL", L"Timor-Leste (TL)" },
    { "TG", L"Togo (TG)" },
    { "TK", L"Tokelau (TK)" },
    { "TO", L"Tonga (TO)" },
    { "TT", L"Trinidad And Tobago (TT)" },
    { "TN", L"Tunisia (TN)" },
    { "TR", L"Turkey (TR)" },
    { "TM", L"Turkmenistan (TM)" },
    { "TC", L"Turks And Caicos Islands (TC)" },
    { "TV", L"Tuvalu (TV)" },
    { "UG", L"Uganda (UG)" },
    { "UA", L"Ukraine (UA)" },
    { "AE", L"United Arab Emirates (AE)" },
    { "GB", L"United Kingdom (GB)" },
    { "US", L"United States (US)" },
    { "UM", L"United States Minor Outlying Islands (UM)" },
    { "UY", L"Uruguay (UY)" },
    { "UZ", L"Uzbekistan (UZ)" },
    { "VU", L"Vanuatu (VU)" },
    { "VE", L"Venezuela (VE)" },
    { "VN", L"Viet Nam (VN)" },
    { "VG", L"Virgin Islands, British (VG)" },
    { "VI", L"Virgin Islands, U.S. (VI)" },
    { "WF", L"Wallis And Futuna (WF)" },
    { "YE", L"Yemen (YE)" },
    { "ZM", L"Zambia (ZM)" },
    { "ZW", L"Zimbabwe (ZW)" },
};
