# The name of our workflow
name: Build
on: [push, pull_request]

jobs:
  checkformat:
    name: "Check code style with clang-format"
    runs-on: ubuntu-24.04
    steps:
      - name: Install pre-commit
        run: pip3 install pre-commit
      - name: Checkout OpenVPN-GUI
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Run pre-commit
        run: pre-commit run -a || true
      - name: Check for changes
        run: git diff --output=cf-changes.patch
      - name: Show changes on standard output
        run: git diff
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cf-changes.patch
          path: cf-changes.patch
      - name: Set job status
        run: test ! -s cf-changes.patch
      - name: Check translations
        run: ./res/cleanup_res_ids.sh

  msvc:
    strategy:
      matrix:
        arch: [x86, x64, arm64]
        conf:
          - name: ""
            value: "release"
        ovpn3:
          - preset: ""
            name: ""
            upload_name: ""
          - preset: -ovpn3
            name: "- ovpn3"
            upload_name: "_ovpn3"
        include:
          - conf:
              name: " ASAN"
              value: "asan"
            arch: x64

    name: 'msvc - ${{matrix.arch}} ${{ matrix.ovpn3.name }}${{ matrix.conf.name }}'
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - uses: lukka/get-cmake@f5b8fbb4d77cec1acc5a5f9f0df4beffaf5d98d9 # v4.3.4

    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: lukka/run-vcpkg@b1a0dd252f06b9e25b3c022a9a03bd7a427fb6a2 # v11.6
      with:
        vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
        vcpkgGitCommitId: 40a9bd4ccdf5dc14ff76d4ed47d46a226ce84a83

    - name: Run CMake consuming CMakePreset.json and vcpkg.json by mean of vcpkg.
      uses: lukka/run-cmake@5d55ea7949e25f69f0ecb516d8d572297e03a956 # v10.9
      with:
        configurePreset: '${{ matrix.arch }}${{ matrix.ovpn3.preset }}'
        buildPreset: '${{ matrix.arch }}-${{ matrix.conf.value }}${{ matrix.ovpn3.preset }}'

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: openvpn-gui_${{ matrix.arch }}_${{ matrix.conf.value }}${{ matrix.ovpn3.upload_name }}
        path: |
          out/build/${{ matrix.arch }}${{ matrix.ovpn3.preset }}/${{ matrix.conf.value }}/*.dll
          out/build/${{ matrix.arch }}${{ matrix.ovpn3.preset }}/${{ matrix.conf.value }}/*.exe

  mingw:
    strategy:
      fail-fast: false
      matrix:
        target: [mingw64, mingw]
        include:
          - target: mingw64
            chost: x86_64-w64-mingw32
          - target: mingw
            chost: i686-w64-mingw32

    name: "gcc-mingw - ${{matrix.target}}"
    runs-on: ubuntu-24.04

    env:
      MAKEFLAGS: -j3

    steps:
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y mingw-w64 libtool automake autoconf
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: autoconf
        run: autoreconf -fvi

      - name: configure
        run: ./configure --host=${{ matrix.chost }}

      - name: make
        run: make
